Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2022-10, with the labels that each got.

#27 FAI-837 - disable failing PMML ITs
  explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
  explainability-integrationtests/explainability-integrationtests-pmml/src/test/java/org/kie/trustyai/explainability/integrationtests/pmml/PmmlCompoundScorecardLimeExplainerTest.java
  explainability-integrationtests/explainability-integrationtests-pmml/src/test/java/org/kie/trustyai/explainability/integrationtests/pmml/PmmlScorecardCategoricalLimeExplainerTest.java
Labels: bug

#26 FAI-839 - perceptron bias update fix, plus enhancements
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/LinearModel.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/DummyModelsLimeExplainerTest.java
Labels: bug, enhancement

#25 FAI-838: Move unit test models to main codebase
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/models/TestModels.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/TestUtils.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/global/lime/AggregatedLimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/global/pdp/PartialDependencePlotExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualDiversifierTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualScoreCalculatorTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/entities/CompositeEntityTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/entities/SimilarityTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/DatasetEncoderTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/DummyModelsLimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/HighScoreNumericFeatureZonesProviderTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/LimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/LimeStabilityTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/optim/LimeCombinedScoreCalculatorTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/optim/LimeConfigEntityFactoryTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/optim/LimeConfigOptimizerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/optim/LimeImpactScoreCalculatorTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/optim/LimeStabilityScoreCalculatorTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/optim/RecordingLimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/shap/ShapConfigTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/shap/ShapKernelExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/shap/ShapResultsTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/shap/ShapSyntheticDataSampleTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/shap/background/CounterfactualGeneratorTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/shap/background/KMeansGeneratorTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/shap/background/RandomGeneratorTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/model/DatasetTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/ExplainabilityMetricsTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/FairnessMetricsTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/ValidationUtilsTest.java
Labels: enhancement

#30 FAI-854 - Avoid gradient explosion in LIME perceptron impl
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/LinearModel.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/DummyModelsLimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/LinearModelTest.java
  explainability-integrationtests/explainability-integrationtests-dmn/src/test/java/org/kie/trustyai/explainability/integrationtests/dmn/DummyDmnModelsLimeExplainerTest.java
  explainability-integrationtests/explainability-integrationtests-dmn/src/test/java/org/kie/trustyai/explainability/integrationtests/dmn/PrequalificationDmnLimeExplainerTest.java
Labels: bug
