Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2022-11, with the labels that each got.

#35 FAI-869: Add Java 17 to CI
  .github/workflows/CI.yaml
Labels: enhancement, pipeline

#38 FAI-862: Update Kogito and OptaPlanner versions
  explainability-integrationtests/explainability-integrationtests-dmn/src/test/java/org/kie/trustyai/explainability/integrationtests/dmn/DummyDmnModelsLimeExplainerTest.java
  pom.xml
Labels: enhancement

#42 FAI-875: LimeConfigOptimizerTest throwing heap space OOM on Java 17
  .github/workflows/CI.yaml
Labels: bug, pipeline, jdk17

#43 FAI-874: Add argument for Java 17 JPMS Arrow tests exception
  pom.xml
Labels: bug, pipeline, jdk17

#44 Surefire heap space OOM fix
  .github/workflows/CI.yaml
  pom.xml
Labels: bug, pipeline, jdk17

#40 FAI-873: Prepare for JBoss deployment
  .gitignore
  explainability-arrow/pom.xml
  explainability-core/pom.xml
  explainability-integrationtests/explainability-integrationtests-dmn/pom.xml
  explainability-integrationtests/explainability-integrationtests-opennlp/pom.xml
  explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
  explainability-integrationtests/pom.xml
  pom.xml
Labels: pipeline

#45 Replace Maven release plugin with versions
  pom.xml
Labels: pipeline

#49 Make it possible to provide predictions to calculate local F1/precision/recall metric
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/lime/ProximityFilter.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/DataUtils.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/ExplainabilityMetrics.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/ExplainabilityMetricsTest.java
Labels: enhancement

#41 Run proximity filter in the original feature space
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/lime/LimeConfig.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/lime/LimeExplainer.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/lime/ProximityFilter.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/lime/SampleWeighter.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/Type.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/DataUtils.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/DummyModelsLimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/SampleWeighterTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/DataUtilsTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/ExplainabilityMetricsTest.java
Labels: enhancement
