Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2022-07, with the labels that each got.

#3 FAI-779: Add support for pluggable CF score calculators
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualExplainer.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/SolverConfigBuilder.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/score/CounterfactualScoreCalculator.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/score/DefaultCounterfactualScoreCalculator.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualScoreCalculatorTest.java
Labels: enhancement

#2 FAI-782: Incorrect instantiation of specific categorical entities in CF
  .gitignore
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/entities/CounterfactualEntityFactory.java
Labels: bug

#4 Add license (ASL-2.0)
  LICENSE
Labels: documentation

#5 FAI-791: Add contributor's guide to trustyai-explainability
  CONTRIBUTING.md
  README.md
Labels: documentation

#7 FAI-792: Add diversity post-processing for counterfactuals
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualDiversifier.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/TestUtils.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualDiversifierTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualScoreCalculatorTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualUtils.java
Labels: enhancement

#10 FAI-803 - LIME to always use executionConfig
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/lime/LimeExplainer.java
Labels: bug

#8 FAI-793: Implement CF programmable goals
  .gitignore
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/LocalExplainer.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualConfig.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualExplainer.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualSolution.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/entities/AbstractCategoricalEntity.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/entities/CounterfactualEntityFactory.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/goal/CounterfactualGoalCriteria.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/goal/DefaultCounterfactualGoalCriteria.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/goal/GoalScore.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/counterfactual/score/DefaultCounterfactualScoreCalculator.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/CounterfactualPrediction.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualScoreCalculatorTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualUtils.java
Labels: enhancement

#15 FAI-808: Add Maven shade plugin
  explainability-core/pom.xml
Labels: enhancement
