Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2023-07, with the labels that each got.

#231 RHODS-8867: Added operator tests to CI
  tests/Makefile
  tests/README.md
  tests/basictests/clean.sh
  tests/basictests/trustyai_biased_models.sh
  tests/basictests/trustyai_odh.sh
  tests/basictests/trustyai_operator.sh
  tests/resources/trustyai/trustyai_crd.yaml
  tests/resources/trustyai/trustyai_operator_configmap.yaml
  tests/resources/trustyai/trustyai_operator_kfdef.yaml
  tests/resources/trustyai/trustyai_service_kfdef.yaml
  tests/resources/utils/send_data_batch
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
  tests/setup/odh-core.yaml
Labels: lgtm, approved, ok-to-test

#229 Added NP + PD support to parsing for both normal + raw cases
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/CodecParameter.java
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/KServeConfig.java
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/KServeV2GRPCPredictionProvider.java
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/PayloadParser.java
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/TensorConverter.java
  explainability-connectors/src/main/java/org/kie/trustyai/explainability/model/TensorDataframe.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/KServeFormatsTest.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/KServePayloads.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/PayloadParserRawTest.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/PayloadParserTest.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/PayloadUtils.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/RawConverterTest.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/TensorConverterTest.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/Dataframe.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/model/DataframeTest.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/InferencePayloadReconciler.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/MetadataUtils.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/consumer/ConsumerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/ExplainerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/global/GlobalExplainerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/LocalExplainerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/GlobalExplanationRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/LocalExplanationRequest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/consumer/ConsumerEndpointFormatsTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/consumer/ConsumerEndpointRawTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/consumer/ConsumerEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/utils/KServePayloads.java
Labels: approved, ok-to-test

#239 Add time-series explainer interface
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/TimeSeriesExplainer.java
Labels: kind/enhancement, lgtm, approved, ok-to-test

#242 Add missing type values
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/Dataframe.java
Labels: kind/bug, lgtm, approved, ok-to-test

#243 Remove old CI test scripts
  tests/basictests/clean.sh
  tests/basictests/trustyai_odh.sh
  tests/resources/trustyai/trustyai_service_kfdef.yaml
Labels: lgtm, approved

#244 Fix CI seds, feature+output names
  tests/basictests/trustyai_biased_models.sh
  tests/basictests/trustyai_operator.sh
  tests/scripts/install.sh
Labels: approved, ok-to-test

#246 Add time-series explanation request payload
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/requests/explainers/ModelConfig.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/requests/explainers/TimeSeriesRequest.java
Labels: kind/enhancement, lgtm, approved, ok-to-test

#248 Added batched NP support to payload parser
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/TensorConverter.java
  tests/basictests/trustyai_biased_models.sh
  tests/resources/data/loan_default_batched/batch_01.json
  tests/resources/data/loan_default_batched/batch_02.json
  tests/resources/data/loan_default_batched/batch_03.json
  tests/resources/data/loan_default_batched/batch_04.json
  tests/resources/data/loan_default_batched/batch_05.json
  tests/resources/data/loan_default_batched/batch_06.json
  tests/resources/data/loan_default_batched/batch_07.json
  tests/resources/data/loan_default_batched/batch_08.json
  tests/resources/data/loan_default_batched/batch_09.json
  tests/resources/data/loan_default_batched/batch_10.json
  tests/resources/data/loan_default_batched/batch_11.json
  tests/resources/data/loan_default_batched/batch_12.json
  tests/resources/data/loan_default_batched/batch_13.json
  tests/resources/trustyai/trustyai_operator_configmap.yaml
  tests/resources/utils/send_data_batch
Labels: approved

#251 Fix Typo in GH Action Reference variable echo
  .github/workflows/build-and-push.yaml
Labels: lgtm, approved

#249 Let hidden "fields" be stored and retrieved correctly
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/Dataframe.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/PredictionMetadata.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/model/DataframeTest.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/DataSource.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/parsers/CSVParser.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/parsers/DataParser.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/CSVUtils.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/InferencePayloadReconciler.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/MetadataUtils.java
  explainability-service/src/test/java/org/kie/trustyai/service/data/DataSourceTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/data/parsers/CSVParserTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/data/utils/CSVUtilsTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/service/ServiceMetadataEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/mocks/MockDatasource.java
Labels: kind/bug, lgtm, approved, ok-to-test

#252 Add tag flow to build-and-push action
  .github/workflows/build-and-push.yaml
Labels: lgtm, approved, ok-to-test

#276 Relax failure conditions of operator cleanup
  tests/basictests/trustyai_biased_models.sh
  tests/basictests/trustyai_operator.sh
Labels: lgtm, approved

#278 Further relax CI deletion reqs
  tests/basictests/trustyai_biased_models.sh
  tests/basictests/trustyai_operator.sh
Labels: lgtm, approved

#277 Use random seed in cf generator
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/shap/background/CounterfactualGenerator.java
Labels: lgtm, approved, ok-to-test

#280 CI Fixes: Remove namespace deletion, add operator waits
  tests/basictests/trustyai_biased_models.sh
  tests/basictests/trustyai_operator.sh
Labels: ok-to-test

#274 Update core readme to reflect modern state of repo
  README.md
Labels: lgtm, approved

#260 Update impsort version and add Maven 3.9.2 to CI matrix
  .github/workflows/CI.yaml
  pom.xml
Labels: kind/bug, approved

#282 Fixed random seeds for LinearModelTest
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/LinearModelTest.java
Labels: kind/bug, approved

#225 Filter out synthetic predictions from bias/fairness metrics calculation
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/Dataframe.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/DummyModelsLimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/model/DataframeTest.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/GroupStatisticalParityDifferenceEndpoint.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/GroupStatisticalParityDifferenceEndpointTest.java
Labels: kind/enhancement, approved, ok-to-test

#287 Add TSSaliency specific request payloads
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/requests/explainers/tssaliency/TSSaliencyParameters.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/requests/explainers/tssaliency/TSSaliencyRequest.java
Labels: kind/enhancement, lgtm, approved, ok-to-test

#288 Make CI data transmission more resiliient
  tests/Makefile
  tests/resources/utils/send_data_batch
Labels: approved, ok-to-test

#293 Add TSSaliency service endpoint
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/tssaliency/TSSaliencyModelWrapper.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/TimeseriesUtils.java
  explainability-service/README.md
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/TSSaliencyEndpoint.java
Labels: kind/enhancement, lgtm, approved, ok-to-test
