Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2023-08, with the labels that each got.

#301 Fix name subsitution in CI
  tests/resources/trustyai/trustyai_operator_kfdef.yaml
  tests/scripts/install.sh
Labels: lgtm, approved, ok-to-test

#275 More comprehensive metric validation, align error message nomenclature
  explainability-service/src/main/java/org/kie/trustyai/service/validators/metrics/fairness/group/GroupMetricRequestValidator.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/RequestPayloadGenerator.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/DisparateImpactRatioEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/scenarios/nodata/DisparateImpactRatioEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/scenarios/nodata/GroupStatisticalParityDifferenceEndpointTest.java
Labels: approved, ok-to-test

#303 Fix Name Mapping integration
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/Dataframe.java
  explainability-service/README.md
  explainability-service/docs/metrics_onboarding.md
  explainability-service/src/main/java/org/kie/trustyai/service/data/DataSource.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/cache/SchemaNameMappingCacheKeyGen.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/metadata/Metadata.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/CSVUtils.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/metrics/RequestReconciler.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/service/Schema.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/values/reconcilable/deserializers/ReconcilableOutputDeserializer.java
  explainability-service/src/main/java/org/kie/trustyai/service/prometheus/PrometheusScheduler.java
  explainability-service/src/main/java/org/kie/trustyai/service/validators/metrics/fairness/group/GroupMetricRequestValidator.java
  explainability-service/src/main/java/org/kie/trustyai/service/validators/metrics/identity/IdentityMetricRequestValidator.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/service/ServiceMetadataEndpointTest.java
  tests/basictests/trustyai_biased_models.sh
  tests/resources/trustyai/trustyai_operator_kfdef.yaml
Labels: lgtm, approved, ok-to-test

#306 Fix prometheus metrics lingering in /q/metrics after deletion
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/BaseEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/prometheus/PrometheusPublisher.java
  explainability-service/src/main/java/org/kie/trustyai/service/prometheus/PrometheusScheduler.java
Labels: lgtm, approved, ok-to-test

#307 fix: Remove obsolete compose demos
  explainability-service/README.md
  explainability-service/demo/compose-generator-memory-multi-model.yaml
  explainability-service/demo/compose-generator-memory-single-model.yaml
  explainability-service/demo/compose-generator-pvc-multi-model.yaml
  explainability-service/demo/compose-generator-pvc-single-model.yaml
  explainability-service/demo/compose-nodata.yaml
  explainability-service/demo/compose.yaml
  explainability-service/demo/logger/logger.Dockerfile
  explainability-service/demo/logger/logger.py
Labels: kind/bug, documentation, approved

#311 Sync issue templates with ODH
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: kind/enhancement, pipeline, lgtm, approved

#313 Update templates from legacy format
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: kind/bug, lgtm, approved

#315 Make individual metrics respect batch size
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/identity/IdentityEndpoint.java
Labels: lgtm, approved, ok-to-test

#312 Drop kserveTarget from ServiceConfig, explainers endpoints package refactoring
  explainability-service/src/main/java/org/kie/trustyai/service/config/ServiceConfig.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/ExplainerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/global/AggregatedLimeEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/global/GlobalExplainerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/global/PartialDependencePlotEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/CounterfactualEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/LimeEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/LocalExplainerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/SHAPEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/TSSaliencyEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/BaseExplanationResponse.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/CounterfactualExplanationRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/CounterfactualExplanationResponse.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/GlobalExplanationRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/LocalExplanationRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/ModelConfig.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/PartialDependencePlotExplanationResponse.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/SaliencyExplanationResponse.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/TimeSeriesRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/tssaliency/TSSaliencyParameters.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/explainers/tssaliency/TSSaliencyRequest.java
  explainability-service/src/main/resources/application.properties
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/global/AggregatedLimeEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/global/PartialDependencePlotEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/local/CounterfactualEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/local/LimeEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/local/ShapEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/mocks/MockMemoryServiceConfig.java
  explainability-service/src/test/java/org/kie/trustyai/service/mocks/MockPVCServiceConfig.java
Labels: kind/enhancement, approved, ok-to-test

#316 Remove KSERVE_TARGET from compose demo
  explainability-service/demo/compose-partial-pvc-single-model.yaml
Labels: kind/bug, lgtm, approved

#326 Update base image
  explainability-service/demo/logger/generator.Dockerfile
  explainability-service/demo/logger/partial.Dockerfile
Labels: kind/bug, lgtm, approved, ok-to-test, kind/dependencies

#321 Add default request tags to BaseEndpoint
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/metrics/BaseMetricRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/prometheus/PrometheusPublisher.java
  explainability-service/src/main/java/org/kie/trustyai/service/prometheus/PrometheusScheduler.java
Labels: approved, ok-to-test
