Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2023-05, with the labels that each got.

#162 RHODS-8228: Add guard against batch size larger than data
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/BaseMetricRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/prometheus/PrometheusScheduler.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioRequestsEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/GroupStatisticalParityDifferenceRequestsEndpointTest.java
Labels: bug, module/service

#166 feat: Refactor metrics namespace
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/lime/optim/LimeImpactScoreCalculator.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/local/lime/optim/LimeStabilityScoreCalculator.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/metrics/FairnessMetrics.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/ValidationUtils.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/accuracy/ConfusionMatrix.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/explainability/ExplainabilityMetrics.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/fairness/FairnessDefinitions.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/fairness/FairnessMetricsUtils.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/fairness/group/DisparateImpactRatio.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/fairness/group/GroupAverageOddsDifference.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/fairness/group/GroupAveragePredictiveValueDifference.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/fairness/group/GroupStatisticalParityDifference.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/fairness/individual/IndividualConsistency.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/DummyModelsLimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/LimeStabilityTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/metrics/ExplainabilityMetricsTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/metrics/FairnessMetricsUtilsTest.java
  explainability-integrationtests/explainability-integrationtests-pmml/src/test/java/org/kie/trustyai/explainability/integrationtests/pmml/PmmlCompoundScorecardLimeExplainerTest.java
  explainability-integrationtests/explainability-integrationtests-pmml/src/test/java/org/kie/trustyai/explainability/integrationtests/pmml/PmmlRegressionCategoricalLimeExplainerTest.java
  explainability-integrationtests/explainability-integrationtests-pmml/src/test/java/org/kie/trustyai/explainability/integrationtests/pmml/PmmlRegressionLimeExplainerTest.java
  explainability-integrationtests/explainability-integrationtests-pmml/src/test/java/org/kie/trustyai/explainability/integrationtests/pmml/PmmlScorecardCategoricalLimeExplainerTest.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/GroupStatisticalParityDifferenceEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/MetricsCalculator.java
Labels: enhancement, merge/on-hold

#185 Add OWNERS file
  OWNERS
Labels: enhancement, pipeline, lgtm

#164 Expose explainers endpoints in TrustyAI service
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/KServeV2GRPCPredictionProvider.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/PartialDependenceGraph.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/DataUtils.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/DataUtilsTest.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/ExplainerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/global/AggregatedLimeEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/global/GlobalExplainerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/global/PartialDependencePlotEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/CounterfactualEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/LimeEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/LocalExplainerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/local/SHAPEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/BaseExplanationResponse.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/CounterfactualExplanationRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/CounterfactualExplanationResponse.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/GlobalExplanationRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/LocalExplanationRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/PartialDependencePlotExplanationResponse.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/SaliencyExplanationResponse.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/ExplainersEndpointTestProfile.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/global/AggregatedLimeEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/global/PartialDependencePlotEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/local/CounterfactualEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/local/LimeEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/explainers/local/ShapEndpointTest.java
Labels: enhancement, lgtm, approved

#176 RHODS-7764 - Consume and store gRPC metadata inside PVC
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/InferencePayloadReconciler.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/MetadataUtils.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/consumer/ConsumerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/consumer/InferencePartialPayload.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/consumer/InferencePayload.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/values/DataType.java
Labels: enhancement, approved
