Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2023-06, with the labels that each got.

#194 Fixes Github Build+Push to Use PR SHA + Branch Name
  .github/workflows/build-and-push.yaml
Labels: lgtm, approved

#196 Adds GH Checkout + Label requirements to Push Action
  .github/workflows/build-and-push.yaml
Labels: lgtm, approved

#186 RHODS-8871: Remove mandatory typing from requests
  explainability-service/README.md
  explainability-service/src/main/java/org/kie/trustyai/service/data/cache/MetricCalculationCacheKeyGen.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/metadata/Metadata.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/CSVUtils.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/MetadataUtils.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/GroupStatisticalParityDifferenceEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/MetricsCalculator.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/UniversalListingEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/BaseMetricRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/PayloadConverter.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/ReconciledMetricRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/definitions/DefinitionRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/definitions/ReconciledDefinitionRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/scheduler/ScheduleRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/service/Schema.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/values/DataType.java
  explainability-service/src/main/java/org/kie/trustyai/service/prometheus/PrometheusPublisher.java
  explainability-service/src/main/java/org/kie/trustyai/service/prometheus/PrometheusScheduler.java
  explainability-service/src/main/java/org/kie/trustyai/service/validators/BaseMetricRequestValidator.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioRequestsEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/GroupStatisticalParityDifferenceEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/GroupStatisticalParityDifferenceRequestsEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/RequestPayloadGenerator.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/service/ServiceMetadataEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/scenarios/batching/TestBatching.java
  tests/basictests/trustyai_odh.sh
  tests/scripts/install.sh
  tests/setup/odh-core.yaml
Labels: approved, ok-to-test

#203 Update BRANCH SHA sed
  .github/workflows/build-and-push.yaml
  tests/basictests/trustyai_odh.sh
  tests/scripts/install.sh
Labels: approved, ok-to-test

#206 Fix malformed yaml in build+push action
  .github/workflows/build-and-push.yaml
Labels: lgtm, approved

#208 Removed label check for main-branch builds
  .github/workflows/build-and-push.yaml
Labels: lgtm, approved

#211 Adds Checkout to main-branch action
  .github/workflows/build-and-push.yaml
Labels: lgtm, approved

#217 Add echo of CI image path into "Log reference variables" step
  .github/workflows/build-and-push.yaml
Labels: approved

#219 Update formatting of CI repo print message
  .github/workflows/build-and-push.yaml
Labels: approved

#212 Fix floating-point edge case in payload conversion
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/BaseMetricRequest.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/PayloadConverter.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/GroupStatisticalParityDifferenceEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/RequestPayloadGenerator.java
  explainability-service/src/test/java/org/kie/trustyai/service/payloads/PayloadConverterTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/scenarios/nodata/DisparateImpactRatioEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/scenarios/nodata/GroupStatisticalParityDifferenceEndpointTest.java
Labels: kind/bug, lgtm, approved

#220 RHODS-7764 - filtering DF by id/timestamp/synthetic metadata
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/Dataframe.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/PredictionMetadata.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/model/DataframeTest.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/InferencePayloadReconciler.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/consumer/ConsumerEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/explainers/ExplainerEndpoint.java
Labels: lgtm, approved, ok-to-test, enhancement

#226 Update: base openjdk image set to "latest" tag
  CONTRIBUTING.md
  Dockerfile
  explainability-service/src/main/docker/Dockerfile.jvm
  explainability-service/src/main/docker/Dockerfile.legacy-jar
Labels: lgtm, approved, needs-ok-to-test

#207 RHODS-8306: Feature+output name mapping endpoint
  explainability-service/README.md
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/service/ServiceMetadataEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/service/NameMapping.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/service/Schema.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/service/ServiceMetadataEndpointTest.java
Labels: approved

#237 Remove Prometheus ports
  explainability-service/manifests/base/trustyai-deployment.yaml
  explainability-service/manifests/servicemonitors/trustyai-metrics.yaml
Labels: kind/bug, lgtm, approved
