Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2023-12, with the labels that each got.

#464 Added Gaussian Anomaly Detection functions
  explainability-core/src/main/java/org/kie/trustyai/metrics/anomaly/GaussianAnomalyDetection.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/drift/meanshift/Meanshift.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/utils/PerColumnStatisticalAnalysis.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/utils/PerColumnStatistics.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/anomaly/GaussianAnomalyDetectionTest.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/drift/meanshift/MeanshiftTest.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/utils/PregeneratedNormalData.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/metrics/drift/MeanshiftEndpoint.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/drift/MeanshiftEndpointTest.java
Labels: lgtm, approved, ok-to-test

#472 Update IDE setup
  CONTRIBUTING.md
  config/README.md
  config/eclipse-format.xml
  config/eclipse.importorder
Labels: documentation, kind/enhancement, lgtm, approved

#466 Edit down unit test times
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/DummyModelsLimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/optim/LimeConfigOptimizerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/lime/optim/RecordingLimeExplainerTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/shap/background/CounterfactualGeneratorTest.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/explainability/ExplainabilityMetricsTest.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/explainability/FairnessMetricsUtilsTest.java
Labels: lgtm, approved, ok-to-test

#479 Update Apache Arrow dependency
  explainability-arrow/pom.xml
Labels: lgtm, approved, kind/dependencies

#482 Increase async timeout for CI tests
  .github/workflows/CI.yaml
  explainability-core/src/test/java/org/kie/trustyai/explainability/TestConfig.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/ValidationUtilsTest.java
Labels: lgtm, approved

#481 Change Maven scope of OpenNLP to compile
  explainability-core/pom.xml
  explainability-core/src/test/java/org/kie/trustyai/explainability/utils/ValidationUtilsTest.java
  pom.xml
Labels: kind/enhancement, approved, kind/dependencies

#485 Add MEP, WIL, WIP, Levenshtein
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/AbstractLevenshteinMetric.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/distance/Levenshtein.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/distance/LevenshteinCounters.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/distance/LevenshteinResult.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/levenshtein/ErrorRateResult.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/levenshtein/MatchErrorRate.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/levenshtein/WordErrorRate.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/levenshtein/WordInformationLost.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/levenshtein/WordInformationPreserved.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/match/FuzzyMatch.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/utils/alignment/AlignedTokenSequences.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/utils/alignment/TokenSequenceAligner.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/utils/alignment/TokenSequenceAlignmentCounters.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/wer/WordErrorRate.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/wer/WordErrorRateResult.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/language/levenshtein/LevenshteinCommonTest.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/language/levenshtein/WordErrorRateTest.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/language/utils/alignment/TokenSequenceAlignerTest.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/language/wer/WordErrorRateTest.java
  explainability-core/src/test/java/org/kie/trustyai/validation/explainability/metrics/LevenshteinValidationTest.java
  explainability-core/src/test/resources/validation/README.md
  explainability-core/src/test/resources/validation/metrics/language/glue.csv
Labels: kind/enhancement, lgtm, approved

#487 Add character based Levenshtein distance
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/AbstractLevenshteinMetric.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/distance/Levenshtein.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/distance/LevenshteinCounters.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/language/levenshtein/LevenshteinCommonTest.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/language/levenshtein/WordErrorRateTest.java
  explainability-core/src/test/java/org/kie/trustyai/validation/explainability/metrics/LevenshteinValidationTest.java
Labels: kind/enhancement, lgtm, approved

#488 Add Levenshtein distance matrix to result
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/distance/Levenshtein.java
  explainability-core/src/main/java/org/kie/trustyai/metrics/language/distance/LevenshteinResult.java
  explainability-core/src/test/java/org/kie/trustyai/metrics/language/levenshtein/WordErrorRateTest.java
Labels: kind/enhancement, lgtm, approved
