Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2024-09, with the labels that each got.

#632 Add ODH devflags to GH action comment
  .github/workflows/build-and-push.yaml
Labels: lgtm, ok-to-test

#634 RHOAIENG-12572: Remove signing from shaded JAR as the mixture of signed/unsigned causes problems with Python TrustyAI
  pom.xml
Labels: kind/bug, lgtm, approved, ok-to-test

#631 RHOAIENG-12241: Change metadata field in partial payload from string to text
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/consumer/partial/PartialPayload.java
Labels: lgtm, approved, ok-to-test

#636 Bug: Fix annotation on InferenceLoggerOutputObject
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/consumer/InferenceLoggerOutputObject.java
Labels: lgtm, approved, ok-to-test

#635 CI: Redirect debug logs to file, and provide a cleaner stdout
  tests/scripts/installandtest.sh
Labels: lgtm, approved, ok-to-test

#639 RHOAIENG-13242: Update io-grpc from 1.59 to 1.68
  explainability-connectors/pom.xml
Labels: kind/bug, lgtm, approved, ok-to-test, dependencies

#640 RHOAIENG-13242: Override the version of protobuf-java in the service until io-grpc moves from 3.25.3 to 3.25.5
  explainability-service/pom.xml
Labels: kind/bug, lgtm, ok-to-test, dependencies

#642 CI: ODH DSC install robustness
  tests/scripts/install.sh
Labels: lgtm, ok-to-test

#622 Integrate Tensor Type into service consumers and data types
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/PayloadParser.java
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/RawPayloadParser.java
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/RawValueExtractor.java
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/TensorConverter.java
  explainability-connectors/src/main/java/org/kie/trustyai/connectors/kserve/v2/TensorConverterUtils.java
  explainability-connectors/src/main/java/org/kie/trustyai/explainability/model/TensorDataframe.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/KServeFormatsTest.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/PayloadParserRawTest.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/RawValueExtractorTest.java
  explainability-connectors/src/test/java/org/kie/trustyai/connectors/kserve/v2/TensorConverterTest.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/FeatureFactory.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/Type.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/Value.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/tensor/Tensor.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/tensor/TensorUtilities.java
  explainability-core/src/main/java/org/kie/trustyai/explainability/utils/IOUtils.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/model/TypeTest.java
  explainability-core/src/test/java/org/kie/trustyai/explainability/model/tensor/TensorUtilitiesTest.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/datasources/CSVDataSource.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/parsers/CSVParser.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/CSVUtils.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/KServePayloadConverters.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/MetadataUtils.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/PayloadConverter.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/values/DataType.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/consumer/ConsumerEndpointRawTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/consumer/base/ConsumerEndpointBaseTest.java
Labels: ok-to-test
