Repository trustyai-explainability/trustyai-explainability, pull requests merged in 2025-02, with the labels that each got.

#668 Increase SHAP CF Generator test timeouts
  explainability-core/src/test/java/org/kie/trustyai/explainability/local/shap/background/CounterfactualGeneratorTest.java
Labels: lgtm, approved, ok-to-test

#670 Update owners and PR template
  .github/pull_request_template.md
  OWNERS
Labels: lgtm, approved

#672 fix(CVE-2025-24970): Override to io.netty:netty-handler@4.1.108.Final
  explainability-service/pom.xml
Labels: kind/bug, lgtm, approved, dependencies

#669 CI: Clean up artifacts directory
  tests/Makefile
  tests/installandtest.sh
Labels: lgtm, approved, ok-to-test

#654 Add Trivy image scanning
  .github/workflows/security.yaml
Labels: kind/enhancement, lgtm, approved

#673 chore: Clean up spurious merge conflict strings in javadoc
  explainability-service/src/main/java/org/kie/trustyai/service/data/storage/flatfile/MemoryStorage.java
Labels: lgtm, ok-to-test

#661 RHOAIENG-18653: Add multi-input support to kserve inference payload parsing
  explainability-core/src/main/java/org/kie/trustyai/explainability/model/tensor/Tensor.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/KServePayloadConverters.java
  explainability-service/src/main/java/org/kie/trustyai/service/data/utils/UploadUtils.java
  explainability-service/src/main/java/org/kie/trustyai/service/endpoints/data/UploadEndpoint.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/data/upload/ModelInferBasePayload.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/data/upload/ModelInferRequestPayload.java
  explainability-service/src/main/java/org/kie/trustyai/service/payloads/data/upload/ModelInferResponsePayload.java
  explainability-service/src/test/java/org/kie/trustyai/service/endpoints/data/UploadEndpointTest.java
  explainability-service/src/test/java/org/kie/trustyai/service/utils/KserveRestPayloads.java
Labels: approved, ok-to-test

#674 fix: Change fail criteria for security scan
  .github/workflows/build-and-push.yaml
  .github/workflows/security.yaml
Labels: kind/enhancement, lgtm, approved, ok-to-test
